### ISSUE TITLE
Make slider keyboard accessible

### ISSUE THREAD

**Issue by StommePoes** [jedrzejchalubek/Glide.js#108]
Hi, my marketer liked your slider, and asked me to implement it (in a pretty basic way, nothing fancy).

The issue is that this isn't keyboard-accessible, which at the very least would prevent some companies and agencies from being able to use your slider. As a developer I like to ensure some basic accessibility too anyways...

So I've modified our copy of the slider to turn all the clickables into button elements (for the bullets, these are still inside LI elements). These automatically accept keyboard focus, and trigger click events with both enter and spacebar keys.
In addition, I've added :focus styles to the :hover styles.

Some browsers put focus on elements clicked with the mouse, and usually the designers don't want those :focus styles to appear then, so we also happen to use a 2-line mouse-detection script so we can say "only show focus styles when no mouse detected" (could also add touch(start/end) to this as well).

Would you like a pull request?

**Comment by jedrzejchalubek** [comment]
Hi, thanks for suggestion, but actually this is pretty simple to accomplish with triggers. They were just made for such cases, if you do not like the default markup.
Here is a demo: http://codepen.io/anon/pen/LVqWwj (styles little broken, but it shows what's going on)

This is a special case for a specific project. I do not want to make it base, a part of the standard markup. There are few reasons for that:
- Plugin isn't actually markup sensitive. If you want button instead of div, just change it.
- Using `<button>` by default will increase css. They have basic styling from bowser that should by cleared. It's better to use something more neutral.

**Comment by StommePoes** [comment]
"Plugin isn't actually markup type sensitive. If you want <button> instead of <a>, just change it."


The markup I found was <span> and <li>, not <a>.  I clicked for the .zip from the site (not Github), is that out of date? If I made an issue about outdated code, I apologise.
<a>, while being a bit less semantically correct than a button, is otherwise keyboardable out of the box already, no problems. I wouldn't have made an issue over those.

The stuff I changed wasn't really the direction ones (prev/next), you're right that changing the markup to whatever is purely markup there. No problems. But the bullets I did change: because I added children to the li's I shifted the CSS and events from the li's to li.children() etc. I actually only added one property for the buttons, padding. The li styling you have already overrode most of the default browser button stuff (yay).

:focus styles are great but they only have meaning on focusables, so the bullets, if still only <li> elements, wouldn't do anything.
...Unless you meant maybe "li *:focus" for if any of us add buttons/anchors/whatever as children. That would work.

**Comment by MichielBijl** [comment]
“This is a special case for a specific project” accessibility is not “specific” for a “specific project”; it's a universal need and one of the foundations of the internet.

<blockquote>
<p>The power of the Web is in its universality.
Access by everyone regardless of disability is an essential aspect.</p>
<footer>—Tim Berners-Lee, W3C Director and inventor of the World Wide Web</footer></blockquote>

As stated in the specification:

<blockquote>
<p>These are links to other resources that are generally exposed to the user by the user agent so that the user can cause the user agent to navigate to those resources, e.g. to visit them in a browser or download them.</p>
<footer>Source: [HTML5 Specification on hyperlinks](http://www.w3.org/TR/html5/links.html#hyperlink) (which `<a>` is)</footer>
</blockquote>

One could argue that an anchor is the correct element for the purpose of moving to other content in the slider, but then they would have to contain an `href` linked to an ID (of the slide that is navigated to).

If that is not the case, a [`<button>`-element](http://www.w3.org/TR/html5/forms.html#the-button-element) is more suitable. The use of `<li>`'s for navigation is only acceptable if you mark them up as buttons and add JavaScript to handle the various keyboard events.

The number of lines you need to capture keyboard events far outnumber the lines of CSS you'll need to style `<button>`'s the way you want.

Good to hear you will include `:focus` styles!

**Comment by StommePoes** [comment]
Sorry @MichielBijl, I had looked at the CodePen but I'm not good at reading pre-HTML thingies and had missed that the buttons were *replacing* the li's.

**Comment by MichielBijl** [comment]
@StommePoes okay, but what about the [example on the Glide homepage](http://glide.jedrzejchalubek.com/)? That uses `<div>`'s and `<li>`'s for the navigation.

P.S. you can click 'View compiled' to view the compiled code :)

**Comment by StommePoes** [comment]
@MichielBijl duh, I'm so not a code-penner.  : P 

I noticed the examples were different from what you see in the live versions, so they're probably simply out of date. I figure a lot of devs would be inspecting the 2 examples he's got rather than only copying the example HTML... I did. : )

**Comment by jedrzejchalubek** [comment]
Ok, you convinced me :) I appoint it to the next version. Maybe to that time anyone else terminates.
For now, as i mentioned, it's possible to achieve via triggers without digging into source.

@StommePoes Where are these examples? I don't see anywhere outdated ones.

**Comment by MichielBijl** [comment]
:+1: Awesome! If you need any help regarding accessibility; you know where to find us.

**Comment by StommePoes** [comment]
@jedrzejchalubek  Hi, on the Docs page under the heading "Setup", you've got an example HTML chunk.   Even though developers are encouraged to use whatever markup they need, for many people they're going to see that example and figure it's good enough. I would think probably most people just copy that code and make slight adjustments, rather than writing something entirely new.

But above that part, you've got a running-example slider, the #demo-paddings one. Here, for the bullets you're using something actually invalid (&lt;li&gt;'s can't be children of &lt;div&gt;s, .glide-bullets would need to be a &lt;ul&gt;), but the idea is good --  a list of bullets makes sense just as a list of navigation links makes sense as a list too.  I also used the ul-li setup for the main panels too -- which you did on the working-example on the home page #Slider.

So I thought your working examples to be more "updated" than the markup sample under Setup, but that was a guess. Maybe you created them all at the same time :)

In any case, except for the error of div-li, it's a semantics argument. You don't *have* to do everything in lists. Accessibility-wise, lists have a slight advantage because some Access Technology (like screen readers) can let a user know right away how many items are in a list, which can be handy. But an example composed entirely of divs and buttons can still function properly and can be keyboard-accessible. 

So I encourage the lists (ul) you used, but don't demand them.

**Comment by jedrzejchalubek** [comment]
v2.0.4

**Comment by StommePoes** [comment]
cooooool :)
