### ISSUE TITLE
Type: `slideshow` shows nothing

### ISSUE THREAD

**Issue by bfintal** [jedrzejchalubek/Glide.js#142]
The slider doesn't appear when using `type: 'slideshow'`. Nothing fancy with my implementation, It's just

    jQuery( element ).glide({
        type: 'slideshow'
    });

**Comment by jedrzejchalubek** [comment]
Provide so more details. Console show up any errors? Are u sure u implemented it right (especially CSS).

**Comment by bfintal** [comment]
Hi, I just followed the typical setup and added in the theme css and core css along with the core js. Using the other types work fine without any arguments. But once I use `slideshow`, the bullets are there but the slides aren't visible.

**Comment by jedrzejchalubek** [comment]
Make sure that slide content or slider container have fixed height.

**Comment by bfintal** [comment]
I added some height to `.glide--carousel` or `.glide__wrapper` to make it show up. But I think it would be better if it worked even without explicitly specifying the height like the `slider` or `carousel` types.

**Comment by bfintal** [comment]
See this pen: http://codepen.io/bfintal/pen/RreadX
All the CSS & JS there are just copies of what's needed by Glide. See the bottom of the JS for the initialization.

**Comment by jedrzejchalubek** [comment]
Glide basic height styling is set up to `100%`. Adding fixed height out of the box does not make sense, because everybody will have to modify or overwrite that.

Putting slider inside wrapper with fixed height is the best way. You don't need to touch glide styles itself. Slider will take 100% of his parent height.

On the other hand, you can always add your own class to slider main markup and set up height for that. After updating plugin, height will not be overwritten.
